# Generated by Django 5.2.7 on 2025-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320)),
                ('telefono', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('constraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
